# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20161116_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[(b'OK', b'Geladen'), (b'im Lager', b'Im Lager')], default='im Lager', max_length=8),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Equipment'),
        ),
    ]
