# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20161117_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'bereit', b'bereit'), (b'nicht bereit', b'nicht bereit')], default='nicht bereit', max_length=11),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Equipment'),
        ),
    ]
