# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20161117_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Equipment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'glyphicon glyphicon-ok', b'bereit'), (b'glyphicon glyphicon-remove', b'nicht bereit')], default='glyphicon glyphicon-remove', max_length=30),
        ),
    ]
