# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20161227_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='event',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Equipment'),
        ),
    ]
