# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20161230_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='order',
            new_name='orders',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='storage.Equipment'),
        ),
    ]
