# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20170103_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='location',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='storage.Equipment'),
        ),
    ]
