# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_auto_20170130_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='storage.Equipment'),
        ),
    ]
