# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('post_code', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('assignments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.client')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fabricator', models.CharField(default='-', max_length=30)),
                ('storeplace', models.IntegerField()),
                ('labor', models.CharField(choices=[(b'L', b'Licht'), (b'T', b'Ton'), (b'R', b'rigging')], max_length=1)),
                ('max_quantity', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Type', models.CharField(choices=[(b'R', b'Rental'), (b'FS', b'Full Service')], default='Rental', max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('GuestNumber', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='event',
            field=models.ManyToManyField(blank=True, through='manager.Assignment', to='manager.Order'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Equipment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Order'),
        ),
    ]
