# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20161113_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='event',
            new_name='orders',
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[(b'OK', b'Geladen'), (b'im Lager', b'Im Lager')], default='im Lager', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'ok', b'bereit'), (b'notOK', b'nicht bereit')], default='notOK', max_length=30),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='manager.Equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='storeplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.shelf'),
        ),
    ]
