# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170124_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Image',
            field=models.ImageField(null=True, upload_to='product_pics'),
        ),
    ]
