# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170126_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='labor',
            field=models.CharField(choices=[('L', 'Licht'), ('T', 'Ton'), ('R', 'rigging')], max_length=1),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('OK', 'Geladen'), ('im Lager', 'Im Lager')], default='im Lager', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='Type',
            field=models.CharField(choices=[('R', 'Rental'), ('FS', 'Full Service')], default='Rental', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ok', 'bereit'), ('notOK', 'nicht bereit')], default='notOK', max_length=30),
        ),
    ]
