# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20170128_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='beschreibung',
            field=models.CharField(max_length=1000),
        ),
    ]
