# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170130_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='beschreibung',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
