# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170130_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Image',
            field=models.ImageField(default='../Media/product_pics/no_image.png', upload_to='product_pics'),
        ),
    ]
