# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20170201_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='dateEnd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dateStart',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='GuestNumber',
            field=models.IntegerField(null=True),
        ),
    ]
