# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20170217_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='orders',
            new_name='assignments',
        ),
    ]
