# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20170304_1622'),
        ('manager', '0022_auto_20170226_1853'),
    ]

    operations = [
    ]
